export const shopCredientials = {
  abi: [
    {
      type: "constructor",
      inputs: [
        { name: "_token", type: "address", internalType: "address" },
        { name: "_ico_address_", type: "address", internalType: "address" },
      ],
      stateMutability: "nonpayable",
    },
    { type: "receive", stateMutability: "payable" },
    {
      type: "function",
      name: "Customers",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "clientTransactions",
      inputs: [
        { name: "", type: "address", internalType: "address" },
        { name: "", type: "uint256", internalType: "uint256" },
      ],
      outputs: [
        { name: "date", type: "uint256", internalType: "uint256" },
        { name: "category", type: "string", internalType: "string" },
        { name: "amount", type: "uint256", internalType: "uint256" },
        { name: "etherAmountPaid", type: "uint256", internalType: "uint256" },
        { name: "addressFrom", type: "address", internalType: "address" },
        { name: "addressTo", type: "address", internalType: "address" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getClientTransactions",
      inputs: [{ name: "_address", type: "address", internalType: "address" }],
      outputs: [
        {
          name: "",
          type: "tuple[]",
          internalType: "struct Shop.Transaction[]",
          components: [
            { name: "date", type: "uint256", internalType: "uint256" },
            { name: "category", type: "string", internalType: "string" },
            { name: "amount", type: "uint256", internalType: "uint256" },
            {
              name: "etherAmountPaid",
              type: "uint256",
              internalType: "uint256",
            },
            { name: "addressFrom", type: "address", internalType: "address" },
            { name: "addressTo", type: "address", internalType: "address" },
          ],
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getTransactionCount",
      inputs: [{ name: "_address", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "grantRole",
      inputs: [{ name: "_address", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "offerCoin",
      inputs: [],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "recordTransaction",
      inputs: [
        { name: "category", type: "string", internalType: "string" },
        { name: "tokenAmount", type: "uint256", internalType: "uint256" },
        { name: "etherAmountPaid", type: "uint256", internalType: "uint256" },
        { name: "addressFrom", type: "address", internalType: "address" },
        { name: "_receiver", type: "address", internalType: "address" },
        { name: "account", type: "address", internalType: "address" },
      ],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "redeemEBT",
      inputs: [
        { name: "_tokenAmount", type: "uint256", internalType: "uint256" },
      ],
      outputs: [
        { name: "", type: "bool", internalType: "bool" },
        { name: "", type: "bytes", internalType: "bytes" },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "revokeRole",
      inputs: [{ name: "_address", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "rewardStakers",
      inputs: [],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "roles",
      inputs: [
        { name: "", type: "address", internalType: "address" },
        { name: "", type: "bytes32", internalType: "bytes32" },
      ],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "stake",
      inputs: [{ name: "_amount_", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "stakersBalance",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "startICO",
      inputs: [],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "stopICO",
      inputs: [],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "tokenPrice",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "unstake",
      inputs: [{ name: "_amount_", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "withdraw",
      inputs: [{ name: "_to", type: "address", internalType: "address" }],
      outputs: [
        { name: "", type: "bool", internalType: "bool" },
        { name: "", type: "bytes", internalType: "bytes" },
      ],
      stateMutability: "nonpayable",
    },
  ],
  contractAddress: "0x6C9CE39c60D04Eb38C9b5AB50c00E7E07615F979",
};
