export const marketPlaceCredentials = {
  markePlacetAddress: "0xd7c3e2Cc171597AB643652f118FCbE44AA96929d",
  marketPlaceAbi: [
    {
      type: "constructor",
      inputs: [
        { name: "_token", type: "address", internalType: "address" },
        { name: "_shop", type: "address", internalType: "address" },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "bidForJob",
      inputs: [
        { name: "client", type: "address", internalType: "address" },
        { name: "jobTitle", type: "string", internalType: "string" },
        { name: "budget", type: "uint256", internalType: "uint256" },
        { name: "jobDuration", type: "string", internalType: "string" },
        { name: "_jobID", type: "uint256", internalType: "uint256" },
        { name: "jobDeadline", type: "uint256", internalType: "uint256" },
      ],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "clientReleaseFunds",
      inputs: [{ name: "escrowID", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "closeDispute",
      inputs: [{ name: "escrowID", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "closeEscrow",
      inputs: [{ name: "_escrowID", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "createDispute",
      inputs: [{ name: "escrowID", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "disputeCount",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "escrowCount",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "freelancerEscrows",
      inputs: [
        { name: "", type: "address", internalType: "address" },
        { name: "", type: "uint256", internalType: "uint256" },
      ],
      outputs: [
        { name: "client", type: "address", internalType: "address" },
        { name: "worker", type: "address", internalType: "address" },
        { name: "jobTitle", type: "string", internalType: "string" },
        { name: "budget", type: "uint256", internalType: "uint256" },
        { name: "startTime", type: "uint256", internalType: "uint256" },
        { name: "jobDuration", type: "string", internalType: "string" },
        { name: "isCompleted", type: "bool", internalType: "bool" },
        { name: "inDispute", type: "bool", internalType: "bool" },
        { name: "completedTime", type: "uint256", internalType: "uint256" },
        { name: "_jobID", type: "uint256", internalType: "uint256" },
        {
          name: "vote",
          type: "tuple",
          internalType: "struct MarketPlace.EscrowBallot",
          components: [
            { name: "client", type: "uint256", internalType: "uint256" },
            { name: "worker", type: "uint256", internalType: "uint256" },
          ],
        },
        { name: "escrowID", type: "uint256", internalType: "uint256" },
        { name: "jobDeadline", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getEscrow",
      inputs: [{ name: "escrowID", type: "uint256", internalType: "uint256" }],
      outputs: [
        {
          name: "",
          type: "tuple",
          internalType: "struct MarketPlace.Escrow",
          components: [
            { name: "client", type: "address", internalType: "address" },
            { name: "worker", type: "address", internalType: "address" },
            { name: "jobTitle", type: "string", internalType: "string" },
            { name: "budget", type: "uint256", internalType: "uint256" },
            { name: "startTime", type: "uint256", internalType: "uint256" },
            { name: "jobDuration", type: "string", internalType: "string" },
            { name: "isCompleted", type: "bool", internalType: "bool" },
            { name: "inDispute", type: "bool", internalType: "bool" },
            { name: "completedTime", type: "uint256", internalType: "uint256" },
            { name: "_jobID", type: "uint256", internalType: "uint256" },
            {
              name: "vote",
              type: "tuple",
              internalType: "struct MarketPlace.EscrowBallot",
              components: [
                { name: "client", type: "uint256", internalType: "uint256" },
                { name: "worker", type: "uint256", internalType: "uint256" },
              ],
            },
            { name: "escrowID", type: "uint256", internalType: "uint256" },
            { name: "jobDeadline", type: "uint256", internalType: "uint256" },
          ],
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getJobs",
      inputs: [],
      outputs: [
        {
          name: "",
          type: "tuple[]",
          internalType: "struct MarketPlace.Job[]",
          components: [
            { name: "id", type: "uint256", internalType: "uint256" },
            { name: "postedAt", type: "uint256", internalType: "uint256" },
            { name: "client", type: "address", internalType: "address" },
            { name: "jobTitle", type: "string", internalType: "string" },
            { name: "description", type: "string", internalType: "string" },
            {
              name: "executionDuration",
              type: "string",
              internalType: "string",
            },
            { name: "category", type: "string", internalType: "string" },
            { name: "budget", type: "uint256", internalType: "uint256" },
            {
              name: "executionStatus",
              type: "uint8",
              internalType: "enum MarketPlace.jobExecutionState",
            },
            { name: "deadline", type: "uint256", internalType: "uint256" },
          ],
        },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "getOpenDisputeEscrows",
      inputs: [],
      outputs: [
        {
          name: "",
          type: "tuple[]",
          internalType: "struct MarketPlace.Escrow[]",
          components: [
            { name: "client", type: "address", internalType: "address" },
            { name: "worker", type: "address", internalType: "address" },
            { name: "jobTitle", type: "string", internalType: "string" },
            { name: "budget", type: "uint256", internalType: "uint256" },
            { name: "startTime", type: "uint256", internalType: "uint256" },
            { name: "jobDuration", type: "string", internalType: "string" },
            { name: "isCompleted", type: "bool", internalType: "bool" },
            { name: "inDispute", type: "bool", internalType: "bool" },
            { name: "completedTime", type: "uint256", internalType: "uint256" },
            { name: "_jobID", type: "uint256", internalType: "uint256" },
            {
              name: "vote",
              type: "tuple",
              internalType: "struct MarketPlace.EscrowBallot",
              components: [
                { name: "client", type: "uint256", internalType: "uint256" },
                { name: "worker", type: "uint256", internalType: "uint256" },
              ],
            },
            { name: "escrowID", type: "uint256", internalType: "uint256" },
            { name: "jobDeadline", type: "uint256", internalType: "uint256" },
          ],
        },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "jobCount",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "jobs",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [
        { name: "id", type: "uint256", internalType: "uint256" },
        { name: "postedAt", type: "uint256", internalType: "uint256" },
        { name: "client", type: "address", internalType: "address" },
        { name: "jobTitle", type: "string", internalType: "string" },
        { name: "description", type: "string", internalType: "string" },
        { name: "executionDuration", type: "string", internalType: "string" },
        { name: "category", type: "string", internalType: "string" },
        { name: "budget", type: "uint256", internalType: "uint256" },
        {
          name: "executionStatus",
          type: "uint8",
          internalType: "enum MarketPlace.jobExecutionState",
        },
        { name: "deadline", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "listJob",
      inputs: [
        { name: "jobTitle", type: "string", internalType: "string" },
        { name: "description", type: "string", internalType: "string" },
        { name: "executionDuration", type: "string", internalType: "string" },
        { name: "category", type: "string", internalType: "string" },
        { name: "budget", type: "uint256", internalType: "uint256" },
        { name: "deadline", type: "uint256", internalType: "uint256" },
      ],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "markJobAsComplete",
      inputs: [
        { name: "_jobID", type: "uint256", internalType: "uint256" },
        { name: "escrowID", type: "uint256", internalType: "uint256" },
      ],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "moderatoreReleaseFunds",
      inputs: [{ name: "escrowID", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "stakers",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "startJOb",
      inputs: [
        { name: "_jobID", type: "uint256", internalType: "uint256" },
        { name: "_escrowID", type: "uint256", internalType: "uint256" },
      ],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "unListJob",
      inputs: [{ name: "_jobID", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "userJobs",
      inputs: [
        { name: "", type: "address", internalType: "address" },
        { name: "", type: "uint256", internalType: "uint256" },
      ],
      outputs: [
        { name: "id", type: "uint256", internalType: "uint256" },
        { name: "postedAt", type: "uint256", internalType: "uint256" },
        { name: "client", type: "address", internalType: "address" },
        { name: "jobTitle", type: "string", internalType: "string" },
        { name: "description", type: "string", internalType: "string" },
        { name: "executionDuration", type: "string", internalType: "string" },
        { name: "category", type: "string", internalType: "string" },
        { name: "budget", type: "uint256", internalType: "uint256" },
        {
          name: "executionStatus",
          type: "uint8",
          internalType: "enum MarketPlace.jobExecutionState",
        },
        { name: "deadline", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "voteEscrowDispute",
      inputs: [
        { name: "_escrowID", type: "uint256", internalType: "uint256" },
        { name: "party", type: "uint8", internalType: "uint8" },
      ],
      outputs: [{ name: "success", type: "bool", internalType: "bool" }],
      stateMutability: "nonpayable",
    },
  ],
};
